"""Safe synthetic test data generation."""

from __future__ import annotations

from test_data_agent.agent import (
    AgentApprovalReceipt,
    AgentCompletionCheckpoint,
    AgentFieldReference,
    AgentFieldSummary,
    AgentGenerationSummary,
    AgentNextAction,
    AgentPlanSummary,
    AgentRecoverySummary,
    AgentRequest,
    AgentReviewEntitySummary,
    AgentReviewFieldSummary,
    AgentReviewReport,
    AgentReviewSafetySummary,
    AgentReviewState,
    AgentRelationshipSummary,
    AgentResult,
    AgentSourceType,
    AgentWorkspaceStatus,
    apply_agent_advisor_proposal,
    advise_agent_workspace,
    approve_agent_workspace,
    build_agent_advisor_exchange,
    build_agent_advisor_request,
    detect_agent_source_type,
    inspect_agent_workspace,
    plan_agent_profile,
    plan_agent_request,
    recover_agent_workspace,
    review_agent_workspace,
)
from test_data_agent.advisor import (
    AdvisorContractError,
    AdvisorExchange,
    AdvisorExchangeClient,
    AdvisorProposal,
    AdvisorRequest,
    AdvisorReviewArtifact,
    DatasetAdvisor,
    ExchangeDatasetAdvisor,
    advise_dataset_spec,
    advisor_proposal_json_schema,
    build_advisor_exchange,
    build_advisor_request,
    build_advisor_review_artifact,
    validate_advisor_proposal,
)
from test_data_agent.core import DATASET_SPEC_SCHEMA_VERSION, DatasetProfile, DatasetSpec
from test_data_agent.cli_contract import CliErrorCode, CliErrorDetail, CliErrorResponse
from test_data_agent.generation import generate_dataset, infer_dataset_spec, solve_constraints
from test_data_agent.io.workflows import DatasetGenerationResult, generate_dataset_bundle
from test_data_agent.validation import DatasetValidationReport, validate_dataset
from test_data_agent.version import __version__

__all__ = [
    "AgentApprovalReceipt",
    "AgentCompletionCheckpoint",
    "AgentFieldReference",
    "AgentFieldSummary",
    "AgentRequest",
    "AgentReviewEntitySummary",
    "AgentReviewFieldSummary",
    "AgentReviewReport",
    "AgentReviewSafetySummary",
    "AgentReviewState",
    "AgentRelationshipSummary",
    "AgentResult",
    "AgentPlanSummary",
    "AgentRecoverySummary",
    "AgentGenerationSummary",
    "AgentNextAction",
    "AgentSourceType",
    "AgentWorkspaceStatus",
    "AdvisorContractError",
    "AdvisorExchange",
    "AdvisorExchangeClient",
    "AdvisorProposal",
    "AdvisorRequest",
    "AdvisorReviewArtifact",
    "CliErrorCode",
    "CliErrorDetail",
    "CliErrorResponse",
    "DatasetProfile",
    "DatasetSpec",
    "DatasetGenerationResult",
    "DatasetAdvisor",
    "ExchangeDatasetAdvisor",
    "DatasetValidationReport",
    "DATASET_SPEC_SCHEMA_VERSION",
    "apply_agent_advisor_proposal",
    "approve_agent_workspace",
    "advise_agent_workspace",
    "advise_dataset_spec",
    "advisor_proposal_json_schema",
    "build_agent_advisor_exchange",
    "build_agent_advisor_request",
    "build_advisor_exchange",
    "build_advisor_request",
    "build_advisor_review_artifact",
    "detect_agent_source_type",
    "generate_dataset",
    "generate_dataset_bundle",
    "infer_dataset_spec",
    "inspect_agent_workspace",
    "plan_agent_request",
    "plan_agent_profile",
    "recover_agent_workspace",
    "review_agent_workspace",
    "solve_constraints",
    "validate_dataset",
    "validate_advisor_proposal",
    "__version__",
]
